import Head from 'next/head'
import Image from 'next/image'
import Axios from 'axios'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'

export default function Home() {
  const [phone, setPhone] = useState()
  const [firstName, setFirstName] = useState()
  const [lastName, setLastName] = useState()
  const [email, setEmail] = useState()
  const [amount, setAmount] = useState()

  const [data, setData] = useState([])
  const [error, setError] = useState()
  const [buttonText, setButtonText] = useState('Pay')

  const router = useRouter()

  const payHandler = (event) => {
    event.preventDefault()
    setButtonText('Processing')

    Axios.post('https://sandbox.intasend.com/api/v1/checkout/', {
      public_key: 'ISPubKey_test_146fe58b-5b1c-46aa-8af8-1d4b308569f8',
      first_name: firstName,
      last_name: lastName,
      email: email,
      phone_number: phone,
      host: 'https://civrot.com',
      amount,
      currency: 'KES',
    })
      .then((res) => {
        setData(res.data)
        router.push(res.data.url)
        console.log(res)
      })
      .catch((error) => {
        console.log(error)
        setButtonText('Error')
      })
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="shadow-sm shadow-gray-300 px-10  rounded-2xl  my-6 justify-center items-center  flex flex-col">
        <h1 className="text-xl p-2">
          Pay with <span className="text-green-600  font-bold">Mpesa/Bank</span>
        </h1>
        <form className="flex flex-col p-6 space-y-5">
          {' '}
          <input
            onChange={(e) => setFirstName(e.target.value)}
            placeholder="First Name"
            className=" bg-slate-200 left-0 text-black  py-1 px-2 outline-none  rounded-xl"
          />{' '}
          <input
            onChange={(e) => setLastName(e.target.value)}
            placeholder="Last Name"
            className=" bg-slate-200 left-0 text-black  py-1 px-2 outline-none  rounded-xl"
          />{' '}
          <input
            onChange={(e) => setPhone(e.target.value)}
            placeholder="Phone"
            className=" bg-slate-200 text-black py-1 px-2 outline-none  rounded-xl"
          />
          <input
            onChange={(e) => setEmail(e.target.value)}
            placeholder="Email"
            className=" bg-slate-200 left-0 text-black py-1 px-2 outline-none  rounded-xl"
          />{' '}
          <input
            name="Ksh"
            onChange={(e) => setAmount(e.target.value)}
            placeholder="Amount"
            className=" bg-slate-200 left-0 text-black px-2 py-1 outline-none  rounded-xl"
          />
          <button
            onClick={payHandler}
            disabled={amount && firstName && lastName && email ? false : true}
            className="bg-pink-600 disabled:bg-gray-400 text-white px-2 py-1 rounded-2xl"
          >
            {buttonText}
          </button>
        </form>
      </main>
    </>
  )
}
